### PR TITLE
fix: Cache and reuse Consul watchers

### LINKED ISSUE #190: Looks like watcher cache is never used (consul discovery)
The map is `nil` and never initialized, looks like it was defined to collect the watchers but was never used

https://github.com/jexia/semaphore/blob/master/pkg/discovery/consul/consul.go#L11

### PR DESCRIPTION
**Pull request by veger**
Also get rid of `address` as it is not used.

Fixes #190

### CODE REVIEW

File: pkg/discovery/consul/consul.go [hunk 1]
```diff
@@ -28,20 +28,23 @@ func (c *Consul) Resolver(address string) (discovery.Resolver, error) {
 	}
 
 	name := uri.Host
-
 	if watcher, ok := c.watchers[name]; ok {
 		return watcher, nil
 	}
 
+	// Create a new watcher
```
Comment (Alma-media) [inline pkg/discovery/consul/consul.go:35]: new watcher?

Comment (veger) [reply pkg/discovery/consul/consul.go:35]: if there is no watcher in the cache already

**Review by Alma-media — APPROVED** [review]
